parameters:
  - name: environmentName
    type: string

  - name: variableFile
    type: string

stages:
  - stage: Deploy

    displayName: Deploy Stage

    condition: succeeded()

    variables:
      - template: ../${{ parameters.variableFile }}

    jobs:
      - template: ../templates/deploy.yml

        parameters:
          environmentName: ${{ parameters.environmentName }}
