stages:
  - stage: Quality
    displayName: Quality Stage

    dependsOn: Build
    condition: succeeded()

    jobs:
      - template: ../templates/test-results.yml

      - template: ../templates/sonarqube.yml

      - template: ../templates/security-scan.yml
