variables:
  environmentName: "PROD"

  resourceGroup: "rg-finops360-prod"

  appServiceName: "finops360-prod"

  containerRegistry: "finops360.azurecr.io"

  keyVaultName: "kv-finops360-prod"

  databaseName: "finops360_prod"

  azureSubscription: "Azure-PROD"

  environmentUrl: "https://finops360.com"

  deploymentSlot: "production"

  variableGroup: "VG-FinOps360-PROD"

  keyVaultSecretPrefix: "prod"
