variables:
  environmentName: "UAT"

  resourceGroup: "rg-finops360-uat"

  appServiceName: "finops360-uat"

  containerRegistry: "finops360uat.azurecr.io"

  keyVaultName: "kv-finops360-uat"

  databaseName: "finops360_uat"

  azureSubscription: "Azure-UAT"

  environmentUrl: "https://uat.finops360.com"

  deploymentSlot: "staging"

  variableGroup: "VG-FinOps360-UAT"
