jobs:

- job: BuildBackend

  displayName: Build Backend

  steps:

  - checkout: self
  - template: cache.yml

  - script: |
      echo "Repository Downloaded"
      pwd
      ls -la

    displayName: Verify Checkout

  - task: JavaToolInstaller@0

    displayName: Install Java

    inputs:
      versionSpec: $(javaVersion)
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled

  - script: |
      cd $(backendPath)
      mvn clean verify

    displayName: Maven Verify