jobs:

- job: BuildFrontend

  displayName: Build Frontend

  steps:

  - checkout: self

  - task: NodeTool@0

    displayName: Install Node.js

    inputs:
      versionSpec: $(nodeVersion)

  - script: |
      cd $(frontendPath)
      npm install
      npm run build

    displayName: Build React Application