parameters:

- name: environmentName
  type: string

jobs:

- deployment: Deploy

  displayName: Deploy

  environment: ${{ parameters.environmentName }}

  strategy:

  rolling:

    maxParallel: 1

    preDeploy:

      steps:

        - script: |
            echo "Pre-Deployment Validation"

          displayName: Pre Deployment

    deploy:

      steps:

        # Checkout Repository
        - checkout: self
        - template: keyvault.yml

        # Download Backend Artifact
        - download: current
          artifact: backend

        # Download Frontend Artifact
        - download: current
          artifact: frontend

        # Verify Download
        - script: |
            echo "======================================="
            echo "Downloaded Artifacts"
            echo "======================================="

            ls -R $(Pipeline.Workspace)

          displayName: Verify Downloaded Artifacts

        # Start Deployment
        - script: |
            echo "======================================="
            echo "Deploying FinOps360"
            echo "======================================="

            echo "Environment : ${{ parameters.environmentName }}"
            echo "Application : $(applicationName)"
            echo "Version     : $(artifactVersion)"
            echo "Image Tag   : $(imageTag)"
            echo "Environment : $(environmentName)"

          displayName: Start Deployment

        # Verify Docker
        - script: |
            echo "Docker Version"

            docker --version

            echo ""

            echo "Docker Images"

            docker images

          displayName: Verify Docker Runtime

        # Simulated Deployment
        - script: |
            echo "Deploying Backend..."

            echo "Deploying Frontend..."

            echo "Deployment Completed"

          displayName: Deploy Application

        # Health Check
        - template: health-check.yml
          condition: succeeded()

        # Rollback
        - template: rollback.yml
          condition: failed()

            routeTraffic:

      steps:

        - script: |
            echo "Routing Traffic"

          displayName: Route Traffic

    postRouteTraffic:

      steps:

        - script: |
            echo "Post Deployment Validation"

          displayName: Post Deployment Validation

    on:

      failure:

        steps:

          - script: |
              echo "Deployment Failed"

          displayName: Deployment Failure

      success:

        steps:

          - script: |
              echo "Deployment Successful"

          displayName: Deployment Success
        - template: notifications.yml