jobs:

- deployment: DeployDEV

  displayName: Deploy to DEV

  environment: DEV

  strategy:

    runOnce:

      deploy:

        steps:

        # Checkout Repository
        - checkout: self

        # Download Backend Artifact
        - download: current
          artifact: backend

        # Download Frontend Artifact
        - download: current
          artifact: frontend

        # Verify Download
        - script: |
            echo "======================================="
            echo "Downloaded Artifacts"
            echo "======================================="

            ls -R $(Pipeline.Workspace)

          displayName: Verify Downloaded Artifacts

        # Start Deployment
        - script: |
            echo "======================================="
            echo "Deploying FinOps360"
            echo "======================================="

            echo "Environment : DEV"
            echo "Build Number: $(Build.BuildNumber)"

          displayName: Start Deployment

        # Verify Docker
        - script: |
            echo "Docker Version"

            docker --version

            echo ""

            echo "Docker Images"

            docker images

          displayName: Verify Docker Runtime

        # Simulated Deployment
        - script: |
            echo "Deploying Backend..."

            echo "Deploying Frontend..."

            echo "Deployment Completed"

          displayName: Deploy Application

        # Health Check
        - template: health-check.yml

        # Rollback
        - template: rollback.yml