jobs:

- job: DockerBuild

  displayName: Docker Build

  dependsOn:
    - BuildBackend
    - BuildFrontend

  steps:

  - checkout: self

  - script: |
      echo "Building Backend Docker Image..."

      docker build \
        -t $(applicationName)-backend:$(imageTag) \
        -t $(applicationName)-backend:$(imageLatest) \
        backend

    displayName: Build Backend Docker Image

  - script: |
      echo "Building Frontend Docker Image..."

      docker build \
        -t $(applicationName)-frontend:$(imageTag) \
        -t $(applicationName)-frontend:$(imageLatest) \
        frontend

    displayName: Build Frontend Docker Image

  - script: |
      docker images | grep finops360

    displayName: Verify Docker Images