jobs:

- job: PublishArtifacts

  displayName: Publish Build Artifacts

  dependsOn:
    - DockerBuild

  steps:

  - publish: backend/target
    artifact: backend

  - publish: frontend/dist
    artifact: frontend