jobs:

- job: SecurityScan

  displayName: Security Scan

  dependsOn:
    - SonarQube

  steps:

  - script: |
      echo "Running OWASP Dependency Check..."
      echo "Scanning Maven Dependencies..."

    displayName: Dependency Scan