trigger:
  - dev

pool:
  vmImage: ubuntu-ubuntu-latest

stages:
  - stage: Build

    jobs:
      - job: Backend

        steps:
          - checkout: self
          - script: |
              echo "Building Backend"

            displayName: Build Backend

      - job: Frontend

        steps:
          - checkout: self
          - script: |
              echo ""Building Frontend"

            displayName: Build Frontend
