trigger:
  branches:
    include:
      - release/*

parameters:
  - name: targetEnvironment
    displayName: Target Environment
    type: string
    default: DEV
    values:
      - DEV
      - UAT
      - PROD

variables:
  - template: variables/common.yml

stages:
  - ${{ if eq(parameters.targetEnvironment, 'DEV') }}:
      - template: stages/deploy.yml
        parameters:
          variableFile: variables/dev.yml

  - ${{ if eq(parameters.targetEnvironment, 'UAT') }}:
      - template: stages/deploy.yml
        parameters:
          variableFile: variables/uat.yml

  - ${{ if eq(parameters.targetEnvironment, 'PROD') }}:
      - template: stages/deploy.yml
        parameters:
          variableFile: variables/prod.yml
