trigger:
  branches:
    include:
      - release/*

parameters:
  - name: targetEnvironment
    displayName: Target Environment
    type: string
    default: DEV
    values:
      - DEV
      - UAT
      - PROD

variables:
  - template: variables/common.yml

stages:
  - template: stages/deploy.yml
    parameters:
      environmentName: ${{ parameters.targetEnvironment }}

      variableFile: variables/${{ lower(parameters.targetEnvironment) }}.yml
