trigger:
  branches:
    include:
      - feature/*

pr:
  branches:
    include:
      - dev

variables:
  - template: variables/common.yml

pool:
  vmImage: $(vmImage)

stages:
  - template: stages/build.yml

  - template: stages/quality.yml

  - template: stages/package.yml

  - template: stages/publish.yml
